{% set name = "harper" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elijah-potter/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f248821524a2b240d47255f2f6ee77c6e906859e2552675407ac36bd8c4db3f3

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }}-cli --help

about:
  home: https://github.com/elijah-potter/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The Grammar Checker for Developers
  dev_url: https://github.com/elijah-potter/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
