context:
  version: "0.43.0"

package:
  name: harper
  version: ${{ version }}

source:
  url: https://github.com/elijah-potter/harper/archive/v${{ version }}.tar.gz
  sha256: c49eefa86b96295ba033c1ab4324d195df26f3caec48ca885003a86ce64dcb63

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - harper-cli --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The Grammar Checker for Developers
  homepage: https://github.com/elijah-potter/harper
  repository: https://github.com/elijah-potter/harper

extra:
  recipe-maintainers:
    - danielnachun
