context:
  version: "2.0.0"

package:
  name: harper
  version: ${{ version }}

source:
  url: https://github.com/elijah-potter/harper/archive/v${{ version }}.tar.gz
  sha256: c9ebde7b159c7491ca3350f7e1706eb7e5c105d0b790e3d2119c31e589c16f20

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - harper-cli --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The Grammar Checker for Developers
  homepage: https://github.com/elijah-potter/harper
  repository: https://github.com/elijah-potter/harper

extra:
  recipe-maintainers:
    - danielnachun
